# 00. Getting Started with TensorFlow: A guide to the fundamentals

## What is tensorflow?

[TensorFlow](https://www.tensorflow.org/) is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

## Why Use Tensorflow?

Rather than building Machine Learning and Deep Learning models from scratch, it's more likely you'll use a library such as Tensorflow. This is because it contains many of the most common Machine Learning functions you'll want to use.

## What we're going to Cover?

Tensorflow is vast. But the main premise is simple: turns data into numbers (tensors) and build machine learning algorithms to find patterns in them. 

In this notebook we cover some of the most fundamentals Tensorflow operations more specificially:

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using `@tf.function` (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

Things to note:

* Many of the conventions here will happen automatically behind the scenes (when you build a model) but it's worth knowing so if you see any of these things, you know what's happening. 
* For any TensorFlow function you see, it's important to be able to check it out in the documentation, for example, going to the Python API docs for all functions and searching for what you need: https://www.tensorflow.org/api_docs/python/ (don't worry if this seems overwhelming at first, with enough practice, you'll get used to navigating the documentaiton).

## Introduction to Tensors 

If you've every used NumPy, [tensors](https://www.tensorflow.org/guide/tensor) are the kind of like NumPy arrays (we'll see more on this later). 

For the shake this notebook and going forward, you can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:

* It could be numbers themselves <br>For example: Using tensors to represent the price of cars.
* It could be an image <br> For example: Using tensors to represent the pixels of image. 
* It could be text  <br> For example: Using tensors to represent word
* It could be some other form of information or data you want to represent with numbers. 

#### Question may arises in our, so what will be the main difference between tensors and NumPy.

The main difference between tensors and Numpy (also known as n-dimensional arrays of number) is that tensors can be used on [GPUs (graphical processing units)](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) and [TPUs (tensor processing units)](https://en.wikipedia.org/wiki/Tensor_processing_unit). 

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

Okay, we've been talking enough about tensors, let's see them.

The first thing we'll do is import TensorFlow under the common alias `tf`.

In [3]:
## Import TensorFlow

import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
print(tf.__version__) # find the version number where number should 2.x+

2.7.0


## Creating Tensors with `tf.constant()`

As mentioned before, in general, you usually won't create tensors yourself. This is because TensorFlow has built-in module such as (such as [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) and [`tf.data`](https://www.tensorflow.org/guide/data)) which are able to read your data sources and automatically convert them to tensors and then later on, nueral network models will process these for us. 

But for now, because we're getting familar with tensors themselves and how to manipulate them, we'll see how we can create them ourselves. 

We'll begin by using [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).

In [4]:
# Create a Scalar (rank 0 tensor)

scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

A Scalar is known as a rank 0 tensor. Because it has no dimensions(it's just a number). 

> 🔑 **Note:** For now, you don't need to know too much about the different ranks of tensors (but we will see more on this later). The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

In [5]:
# check the number of a dimensions of a tensor where ndim stands for number of dimensions

scalar.ndim

0

In [6]:
# create a vector more than 0 dimensions

vector = tf.constant([8, 8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 8], dtype=int32)>

In [7]:
# check the number of a dimensions of our vector tensor

vector.ndim

1

In [9]:
# create a matrix more than 1 dimensions

matrix = tf.constant([[7, 70],
                    [10, 7]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 70],
       [10,  7]], dtype=int32)>

In [10]:
# check the number of the dimensions of matrix

matrix.ndim

2

By Default, TensorFlow Creates tensors with either an `int32` or `float32` datatype.

This is known as [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science) (the higher the number, the more precise the number, the more space it takes up on your computer).

In [11]:
# create the another matrix and define the datatype

another_matrix = tf.constant([[7.,10.],
                             [3., 2.],
                             [8.,9.]], dtype=tf.float16) # specify the datatype with 'dtype'

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7., 10.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
# Even though another matrix contains more numbers, its dimensions stay the same

another_matrix.ndim

2

In [14]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)

tensor = tf.constant([[[3, 2, 1],
                      [6, 5, 4]],
                     [[9, 8, 7],
                      [12, 11, 10]],
                     [[15, 14, 13],
                      [18, 17, 16]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  2,  1],
        [ 6,  5,  4]],

       [[ 9,  8,  7],
        [12, 11, 10]],

       [[15, 14, 13],
        [18, 17, 16]]], dtype=int32)>

In [15]:
tensor.ndim

3

This is known as rank 3 tensor `(tensor with 3 dimensions)`, however a tensor can have an arbitary (unlimited) amount of dimensions

For example you might have turn a series of images into tensors with shape (224, 224, 3, 32), where:

* 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
* 3 is the number of colour channels of image (red, green, and blue).
* 32 is the batch size (the number of images a neural network sees at any one time).

All of the variables we have created are actually tensors. But you may also hear them referred to as their different names (the onces we gave them):

* Scalar: a single number
* Vector: a number with direction (<i>For example: wind speed with direction</i>)
* matrix: a 2-dimensional array of number
* tensor: an n-dimensional array of numbers (<i> Where n can be any number, a 0-dimesions tensor is a scalar, a 1-dimension tensor is a vector</i>)

By research, what we've found is that the term matrix and tensor are often interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

For more on the mathematical difference between scalars, vectors and matrices see the [visual algebra post by Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)